/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uddk.view;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import uddk.controller.BookingsController;
import uddk.controller.RoomsController;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form ListReport
     */
    private int staffId;

    public Home(int staffId) {
        initComponents();
        this.staffId = staffId;
        initTBCheckIn();
        initTBCheckOut();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void initTBCheckIn() {
        Vector data = BookingsController.getCheckInToday();
        tbCheckIn.setModel(new DefaultTableModel((Vector) data.get(0), (Vector) data.get(1)) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    public void initTBCheckOut() {
        Vector data = BookingsController.getCheckOutToday();
        tbCheckOut.setModel(new DefaultTableModel((Vector) data.get(0), (Vector) data.get(1)) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btRoom = new javax.swing.JButton();
        btBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCheckIn = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCheckOut = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCheckIn = new javax.swing.JButton();
        btCheckOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Home");

        btRoom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btRoom.setText("Room");
        btRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRoomActionPerformed(evt);
            }
        });

        btBooking.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btBooking.setText("Booking");
        btBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBookingActionPerformed(evt);
            }
        });

        tbCheckIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCheckIn);

        tbCheckOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbCheckOut);

        jLabel2.setText("Check-In Today");

        jLabel3.setText("Check-Out Today");

        btCheckIn.setText("Check In");
        btCheckIn.setMaximumSize(new java.awt.Dimension(85, 23));
        btCheckIn.setMinimumSize(new java.awt.Dimension(85, 23));
        btCheckIn.setPreferredSize(new java.awt.Dimension(85, 23));
        btCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckInActionPerformed(evt);
            }
        });

        btCheckOut.setText("Check Out");
        btCheckOut.setMaximumSize(new java.awt.Dimension(85, 23));
        btCheckOut.setMinimumSize(new java.awt.Dimension(85, 23));
        btCheckOut.setPreferredSize(new java.awt.Dimension(85, 23));
        btCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addComponent(btCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBookingActionPerformed
        new Bookings(staffId);
        this.dispose();
    }//GEN-LAST:event_btBookingActionPerformed

    private void btRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRoomActionPerformed
        new Room(staffId);
        this.dispose();
    }//GEN-LAST:event_btRoomActionPerformed

    private void btCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckInActionPerformed
        if (tbCheckIn.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Please select at least one record in check-in table!", "Invalid booking", 0);
        } else {
            int bookingId = Integer.parseInt(tbCheckIn.getValueAt(tbCheckIn.getSelectedRow(), 0).toString());
            BookingsController.checkIn(bookingId);
            this.initTBCheckIn();
            this.initTBCheckOut();
        }
    }//GEN-LAST:event_btCheckInActionPerformed

    private void btCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckOutActionPerformed
        if (tbCheckOut.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "Please select at least one record in check-out table!", "Invalid booking", 0);
        } else {
            int bookingId = Integer.parseInt(tbCheckOut.getValueAt(tbCheckOut.getSelectedRow(), 0).toString());
            double total = BookingsController.getTotalRoomPrice(bookingId);
            int confirm = JOptionPane.showConfirmDialog(this, "Total price is $" + total + ". Do you want to check-out?");
            if (confirm == 0) {
                BookingsController.checkOut(bookingId);
                this.initTBCheckOut();
            }
        }
    }//GEN-LAST:event_btCheckOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBooking;
    private javax.swing.JButton btCheckIn;
    private javax.swing.JButton btCheckOut;
    private javax.swing.JButton btRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCheckIn;
    private javax.swing.JTable tbCheckOut;
    // End of variables declaration//GEN-END:variables
}
